### ISSUE TITLE
Could not login - onepub seems to crash

### ISSUE THREAD

**Issue by sigurdm** [onepub-dev/onepub#37]
```
> dart pub global activate onepub
[usual output]
> ~/.pub-cache/bin/onepub login
OnePub version: 1.2.2 

Unhandled exception:
Unsupported operation: Cannot modify unmodifiable map
#0      _UnmodifiableMapMixin.remove (dart:collection/maps.dart:289:5)
#1      new AddPrivateCommand (package:onepub/src/commands/add_private_command.dart:47:23)
#2      new MyRunner (package:onepub/src/global_args.dart:72:18)
#3      new ParsedArgs.withArgs (package:onepub/src/global_args.dart:243:18)
#4      entrypoint (package:onepub/src/entry_point.dart:12:33)
#5      main (file:///usr/local/google/home/sigurdm/.pub-cache/hosted/pub.dartlang.org/onepub-1.2.3/bin/onepub.dart:18:3)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

**Comment by bsutton** [comment]
Fixed in 1.2.4.
Thanks for the report.
